

eureka:
  client:
    service-url:
      defaultZone: http://112.126.102.252:8000/eureka
feign:
  httpclient:
    connection-timeout: 60000
    connection-timer-repeat: 60000

spring:
  application:
    name: wplz-web-jsp1
  messages:
    basename: i18n.login
  thymeleaf:
    cache: false
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 15000
  eureka:
    enabled: true