
server:
  port: 8083
  max-http-header-size: 20480
spring:
  application:
    name: wplz-active-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://112.126.102.252:13306/wlzl?characterEncoding=utf-8&useSSL=false
    username: wlzl
    password: wlzl_Ljc1
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1

eureka:
  client:
    service-url:
      defaultZone: http://112.126.102.252:8000/eureka
  instance:
    prefer-ip-address: true
    ip-address: 112.126.102.252
